### ISSUE TITLE
radio buttons don't tab

### ISSUE THREAD

**Issue by teenie-quaggard** [FACxBeamery/project1#13]
most of the page is accessible by tabbing, but the unselected radio buttons are not!
![Screen Shot 2019-09-13 at 08 40 30](https://user-images.githubusercontent.com/37771591/64845472-2f19a800-d602-11e9-910c-6503f2399ee8.png)

**Comment by thomas-galligan** [comment]
You can cycle through the radio buttons with the <> arrow keys, so we'll close this issue
